// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0SuL90iMoDWglErfW4Osdl6czEN0Mvts',
    appId: '1:211178179169:web:f1fa6485ae9888696d7820',
    messagingSenderId: '211178179169',
    projectId: 'sales-expense-tracker-b8d53',
    authDomain: 'sales-expense-tracker-b8d53.firebaseapp.com',
    storageBucket: 'sales-expense-tracker-b8d53.firebasestorage.app',
    measurementId: 'G-MNRMWHNP71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD65l73RRHYcJR48fPbFTuYdS-mPcWNXlo',
    appId: '1:211178179169:android:074c442a9a67f4ab6d7820',
    messagingSenderId: '211178179169',
    projectId: 'sales-expense-tracker-b8d53',
    storageBucket: 'sales-expense-tracker-b8d53.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0SuL90iMoDWglErfW4Osdl6czEN0Mvts',
    appId: '1:211178179169:web:11f8c1b58ef315c86d7820',
    messagingSenderId: '211178179169',
    projectId: 'sales-expense-tracker-b8d53',
    authDomain: 'sales-expense-tracker-b8d53.firebaseapp.com',
    storageBucket: 'sales-expense-tracker-b8d53.firebasestorage.app',
    measurementId: 'G-X309REL4MF',
  );
}
